### ISSUE TITLE
detector_msg_to_pose_array does not work unter Indigo

### ISSUE THREAD

**Issue by Pandoro** [strands-project/strands_perception_people#118]
When starting the people_tracker_robot.launch with the detector_msg_to_pose_array, the following error is thrown:

``` bash
load_parameters: unable to set parameters (last param was [/mdl_people_tracker/minvel=0.025]): cannot marshal None unless allow_none is enabled
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 298, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 271, in start
    self.runner.launch()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 646, in launch
    self._setup()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 633, in _setup
    self._load_parameters()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 330, in _load_parameters
    r  = param_server_multi()
  File "/usr/lib/python2.7/xmlrpclib.py", line 997, in __call__
    return MultiCallIterator(self.__server.system.multicall(marshalled_list))
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1572, in __request
    allow_none=self.__allow_none)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1085, in dumps
    data = m.dumps(params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 632, in dumps
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 654, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 714, in dump_array
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 654, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 735, in dump_struct
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 654, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 714, in dump_array
    dump(v, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 654, in __dump
    f(self, value, write)
  File "/usr/lib/python2.7/xmlrpclib.py", line 658, in dump_nil
    raise TypeError, "cannot marshal None unless allow_none is enabled"
TypeError: cannot marshal None unless allow_none is enabled
```

The tracker seems to work when commenting out the to pose array part.

**Comment by cdondrup** [comment]
Cannot recreate the error. Will have to try once the robot is back. For now everything seems to work fine.

**Comment by cdondrup** [comment]
Tested it on the robot. Seems to have been caused by an old version of something. The newest version of indigo and people perception don't show this behaviour any more.
I know this answer is not really satisfying, but the problem is solved.
