### ISSUE TITLE
human_trajectory error

### ISSUE THREAD

**Issue by PDuckworth** [strands-project/strands_perception_people#163]
@ferdianjovan please see error:

```
[INFO] [WallTime: 1430919058.167683] human_trajectory is ready...
[INFO] [WallTime: 1430919192.327257] Total trajectories: 1
[INFO] [WallTime: 1430919531.177857] Total trajectories: 2
[INFO] [WallTime: 1430919601.216801] Total trajectories: 3
[INFO] [WallTime: 1430919792.161928] Total trajectories: 4
[INFO] [WallTime: 1430919810.176708] Total trajectories: 5
[INFO] [WallTime: 1430919818.162050] Total trajectories: 6
[INFO] [WallTime: 1430919825.260421] Total trajectories: 7
Traceback (most recent call last):
  File "/home/lucie01/catkin_ws_paul/src/strands_perception_people/human_trajectory/scripts/trajectory_publisher.py", line 182, in <module>
    tp.publish_trajectories()
  File "/home/lucie01/catkin_ws_paul/src/strands_perception_people/human_trajectory/scripts/trajectory_publisher.py", line 174, in publish_trajectories
    self._publish_online_data()
  File "/home/lucie01/catkin_ws_paul/src/strands_perception_people/human_trajectory/scripts/trajectory_publisher.py", line 84, in _publish_online_data
    traj_msg = traj.get_trajectory_message(True)
  File "/home/lucie01/catkin_ws_paul/src/strands_perception_people/human_trajectory/src/human_trajectory/trajectory.py", line 58, in get_trajectory_message
    traj.trajectory_length = self.length[to_index-1] - self.length[from_index]
IndexError: list index out of range
[human_trajectories-1] process has died [pid 5938, exit code 1, cmd /home/lucie01/catkin_ws_paul/src/strands_perception_people/human_trajectory/scripts/trajectory_publisher.py __name:=human_trajectories __log:=/home/lucie01/.ros/log/a8990d2c-f3e1-11e4-827a-843a4b7f0ffc/human_trajectories-1.log].
log file: /home/lucie01/.ros/log/a8990d2c-f3e1-11e4-827a-843a4b7f0ffc/human_trajectories-1*.log
[human_trajectories-1] restarting process
process[human_trajectories-1]: started with pid [11809]
[INFO] [WallTime: 1430919865.720089] Connecting to mongodb...
[INFO] [WallTime: 1430919865.721033] Waiting for services...
[INFO] [WallTime: 1430919865.744937] Done
[INFO] [WallTime: 1430919865.746099] Connecting to topological_map...
[INFO] [WallTime: 1430919865.749252] Creating human_trajectory/trajectories topic...
[INFO] [WallTime: 1430919865.779710] Taking data from /people_tracker/positions...
[INFO] [WallTime: 1430919865.782769] human_trajectory is ready...
[INFO] [WallTime: 1430919885.804886] Total trajectories: 1
```

**Comment by ferdianjovan** [comment]
This errors makes the last trajectory (which is supposed to be the eight trajectory) not be saved.
I will look into that.

**Comment by ferdianjovan** [comment]
Fixed in https://github.com/strands-project/strands_perception_people/pull/165.
